import { useEffect } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { GlassCard } from "@/components/common/GlassCard";
import { AlertOctagon } from "lucide-react";

export const Route = createFileRoute("/disclaimer")({
  head: () => ({
    meta: [
      { title: "Disclaimer — WeatherPulse" },
      {
        name: "description",
        content:
          "Important disclaimer regarding the accuracy and source of weather warnings and forecasts on WeatherPulse.",
      },
    ],
  }),
  component: DisclaimerPage,
});

function DisclaimerPage() {
  useEffect(() => {
    document.title = "Disclaimer — WeatherPulse";
  }, []);

  return (
    <div className="space-y-6 max-w-4xl mx-auto">
      <header>
        <h1 className="text-3xl font-semibold tracking-tight">Disclaimer</h1>
        <p className="text-sm text-muted-foreground">Last updated: June 5, 2026</p>
      </header>

      <GlassCard className="p-6 md:p-8 space-y-6">
        <div className="flex items-center gap-2.5 text-amber-500">
          <AlertOctagon className="size-5" />
          <h2 className="text-lg font-semibold text-foreground">General Disclaimer</h2>
        </div>

        <p className="text-sm text-muted-foreground leading-relaxed">
          The weather forecasts, air quality index (AQI) readings, meteorological overlays,
          warnings, and other data presented on **WeatherPulse** (`https://theweatherpulse.in`) are
          provided **for general informational and educational purposes only**.
        </p>

        <section className="space-y-3">
          <h3 className="text-base font-semibold text-foreground">
            1. No Professional Advice or Official Warnings
          </h3>
          <p className="text-sm text-muted-foreground leading-relaxed">
            The information on this website does not constitute official meteorological advisories,
            warnings, or emergency guidance. Under no circumstances should the forecasts,
            indicators, or notifications displayed on WeatherPulse be used as a primary
            decision-making source for life-safety actions, travel plans during natural disasters,
            flight safety, sailing, or agricultural planning.
          </p>
          <p className="text-sm text-muted-foreground leading-relaxed">
            For official, government-sanctioned weather warnings and bulletins in India, please
            consult the **India Meteorological Department (IMD)** (`https://mausam.imd.gov.in`) or
            your local government emergency services.
          </p>
        </section>

        <section className="space-y-3">
          <h3 className="text-base font-semibold text-foreground">2. Accuracy of Data</h3>
          <p className="text-sm text-muted-foreground leading-relaxed">
            While we strive to ensure that the meteorological feeds retrieved from third-party APIs
            (such as OpenWeatherMap) are current and correct, WeatherPulse makes no representations
            or warranties of any kind, express or implied, about the completeness, accuracy,
            reliability, suitability, or availability of the information, products, services, or
            related graphics contained on the website. Any reliance you place on such information is
            therefore strictly at your own risk.
          </p>
        </section>

        <section className="space-y-3">
          <h3 className="text-base font-semibold text-foreground">
            3. Technical Availability & Faults
          </h3>
          <p className="text-sm text-muted-foreground leading-relaxed">
            Every effort is made to keep the website up and running smoothly. However, WeatherPulse
            takes no responsibility for, and will not be liable for, the website being temporarily
            unavailable due to technical issues beyond our control, or any errors arising from API
            outages, network lags, or leaflet maps layer rendering failures.
          </p>
        </section>

        <section className="space-y-3">
          <h3 className="text-base font-semibold text-foreground">4. External Links & Ads</h3>
          <p className="text-sm text-muted-foreground leading-relaxed">
            Through this website, you may be able to link to other websites which are not under the
            control of WeatherPulse. We have no control over the nature, content, and availability
            of those sites. The inclusion of any links does not necessarily imply a recommendation
            or endorse the views expressed within them.
          </p>
          <p className="text-sm text-muted-foreground leading-relaxed">
            Additionally, advertisements served on this website (such as via Google AdSense) are
            selected and generated by third-party systems. WeatherPulse is not responsible for the
            claims, accuracy, or products advertised in these banners.
          </p>
        </section>
      </GlassCard>
    </div>
  );
}
