/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MapsRouteImport } from './routes/maps'
import { Route as ForecastRouteImport } from './routes/forecast'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AirQualityRouteImport } from './routes/air-quality'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as ApiWeatherForecastRouteImport } from './routes/api/weather/forecast'
import { Route as ApiWeatherCurrentRouteImport } from './routes/api/weather/current'
import { Route as ApiWeatherAirRouteImport } from './routes/api/weather/air'
import { Route as ApiTilesSplatRouteImport } from './routes/api/tiles/$'
import { Route as ApiGeoSearchRouteImport } from './routes/api/geo/search'
import { Route as ApiGeoReverseRouteImport } from './routes/api/geo/reverse'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MapsRoute = MapsRouteImport.update({
  id: '/maps',
  path: '/maps',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastRoute = ForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AirQualityRoute = AirQualityRouteImport.update({
  id: '/air-quality',
  path: '/air-quality',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWeatherForecastRoute = ApiWeatherForecastRouteImport.update({
  id: '/api/weather/forecast',
  path: '/api/weather/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWeatherCurrentRoute = ApiWeatherCurrentRouteImport.update({
  id: '/api/weather/current',
  path: '/api/weather/current',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWeatherAirRoute = ApiWeatherAirRouteImport.update({
  id: '/api/weather/air',
  path: '/api/weather/air',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTilesSplatRoute = ApiTilesSplatRouteImport.update({
  id: '/api/tiles/$',
  path: '/api/tiles/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeoSearchRoute = ApiGeoSearchRouteImport.update({
  id: '/api/geo/search',
  path: '/api/geo/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeoReverseRoute = ApiGeoReverseRouteImport.update({
  id: '/api/geo/reverse',
  path: '/api/geo/reverse',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/air-quality': typeof AirQualityRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/disclaimer': typeof DisclaimerRoute
  '/forecast': typeof ForecastRoute
  '/maps': typeof MapsRoute
  '/privacy': typeof PrivacyRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/api/geo/reverse': typeof ApiGeoReverseRoute
  '/api/geo/search': typeof ApiGeoSearchRoute
  '/api/tiles/$': typeof ApiTilesSplatRoute
  '/api/weather/air': typeof ApiWeatherAirRoute
  '/api/weather/current': typeof ApiWeatherCurrentRoute
  '/api/weather/forecast': typeof ApiWeatherForecastRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/air-quality': typeof AirQualityRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/disclaimer': typeof DisclaimerRoute
  '/forecast': typeof ForecastRoute
  '/maps': typeof MapsRoute
  '/privacy': typeof PrivacyRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
  '/api/geo/reverse': typeof ApiGeoReverseRoute
  '/api/geo/search': typeof ApiGeoSearchRoute
  '/api/tiles/$': typeof ApiTilesSplatRoute
  '/api/weather/air': typeof ApiWeatherAirRoute
  '/api/weather/current': typeof ApiWeatherCurrentRoute
  '/api/weather/forecast': typeof ApiWeatherForecastRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/air-quality': typeof AirQualityRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/disclaimer': typeof DisclaimerRoute
  '/forecast': typeof ForecastRoute
  '/maps': typeof MapsRoute
  '/privacy': typeof PrivacyRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/api/geo/reverse': typeof ApiGeoReverseRoute
  '/api/geo/search': typeof ApiGeoSearchRoute
  '/api/tiles/$': typeof ApiTilesSplatRoute
  '/api/weather/air': typeof ApiWeatherAirRoute
  '/api/weather/current': typeof ApiWeatherCurrentRoute
  '/api/weather/forecast': typeof ApiWeatherForecastRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/air-quality'
    | '/contact'
    | '/cookie-policy'
    | '/disclaimer'
    | '/forecast'
    | '/maps'
    | '/privacy'
    | '/saved'
    | '/settings'
    | '/terms'
    | '/blog/$slug'
    | '/blog/'
    | '/api/geo/reverse'
    | '/api/geo/search'
    | '/api/tiles/$'
    | '/api/weather/air'
    | '/api/weather/current'
    | '/api/weather/forecast'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/air-quality'
    | '/contact'
    | '/cookie-policy'
    | '/disclaimer'
    | '/forecast'
    | '/maps'
    | '/privacy'
    | '/saved'
    | '/settings'
    | '/terms'
    | '/blog/$slug'
    | '/blog'
    | '/api/geo/reverse'
    | '/api/geo/search'
    | '/api/tiles/$'
    | '/api/weather/air'
    | '/api/weather/current'
    | '/api/weather/forecast'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/air-quality'
    | '/contact'
    | '/cookie-policy'
    | '/disclaimer'
    | '/forecast'
    | '/maps'
    | '/privacy'
    | '/saved'
    | '/settings'
    | '/terms'
    | '/blog/$slug'
    | '/blog/'
    | '/api/geo/reverse'
    | '/api/geo/search'
    | '/api/tiles/$'
    | '/api/weather/air'
    | '/api/weather/current'
    | '/api/weather/forecast'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AirQualityRoute: typeof AirQualityRoute
  ContactRoute: typeof ContactRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  DisclaimerRoute: typeof DisclaimerRoute
  ForecastRoute: typeof ForecastRoute
  MapsRoute: typeof MapsRoute
  PrivacyRoute: typeof PrivacyRoute
  SavedRoute: typeof SavedRoute
  SettingsRoute: typeof SettingsRoute
  TermsRoute: typeof TermsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ApiGeoReverseRoute: typeof ApiGeoReverseRoute
  ApiGeoSearchRoute: typeof ApiGeoSearchRoute
  ApiTilesSplatRoute: typeof ApiTilesSplatRoute
  ApiWeatherAirRoute: typeof ApiWeatherAirRoute
  ApiWeatherCurrentRoute: typeof ApiWeatherCurrentRoute
  ApiWeatherForecastRoute: typeof ApiWeatherForecastRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maps': {
      id: '/maps'
      path: '/maps'
      fullPath: '/maps'
      preLoaderRoute: typeof MapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast': {
      id: '/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/air-quality': {
      id: '/air-quality'
      path: '/air-quality'
      fullPath: '/air-quality'
      preLoaderRoute: typeof AirQualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/weather/forecast': {
      id: '/api/weather/forecast'
      path: '/api/weather/forecast'
      fullPath: '/api/weather/forecast'
      preLoaderRoute: typeof ApiWeatherForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/weather/current': {
      id: '/api/weather/current'
      path: '/api/weather/current'
      fullPath: '/api/weather/current'
      preLoaderRoute: typeof ApiWeatherCurrentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/weather/air': {
      id: '/api/weather/air'
      path: '/api/weather/air'
      fullPath: '/api/weather/air'
      preLoaderRoute: typeof ApiWeatherAirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tiles/$': {
      id: '/api/tiles/$'
      path: '/api/tiles/$'
      fullPath: '/api/tiles/$'
      preLoaderRoute: typeof ApiTilesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/geo/search': {
      id: '/api/geo/search'
      path: '/api/geo/search'
      fullPath: '/api/geo/search'
      preLoaderRoute: typeof ApiGeoSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/geo/reverse': {
      id: '/api/geo/reverse'
      path: '/api/geo/reverse'
      fullPath: '/api/geo/reverse'
      preLoaderRoute: typeof ApiGeoReverseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AirQualityRoute: AirQualityRoute,
  ContactRoute: ContactRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  DisclaimerRoute: DisclaimerRoute,
  ForecastRoute: ForecastRoute,
  MapsRoute: MapsRoute,
  PrivacyRoute: PrivacyRoute,
  SavedRoute: SavedRoute,
  SettingsRoute: SettingsRoute,
  TermsRoute: TermsRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ApiGeoReverseRoute: ApiGeoReverseRoute,
  ApiGeoSearchRoute: ApiGeoSearchRoute,
  ApiTilesSplatRoute: ApiTilesSplatRoute,
  ApiWeatherAirRoute: ApiWeatherAirRoute,
  ApiWeatherCurrentRoute: ApiWeatherCurrentRoute,
  ApiWeatherForecastRoute: ApiWeatherForecastRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
